In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

## Basic Training in TF

In [2]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(10000):
  _, loss_value = sess.run((train, loss))
  if(i%100 == 0):
        print(loss_value)

0.32181293
0.08346121
0.045819238
0.025154209
0.013809346
0.00758118
0.0041619595
0.0022848602
0.0012543576
0.00068862515
0.00037804793
0.00020754497
0.00011393815
6.254967e-05
3.433878e-05
1.8852035e-05
1.0349323e-05
5.682139e-06
3.1195354e-06
1.7127527e-06
9.403159e-07
5.162974e-07
2.834607e-07
1.556813e-07
8.55142e-08
4.699451e-08
2.5821787e-08
1.4204037e-08
7.82966e-09
4.3305874e-09
2.3863826e-09
1.3138113e-09
7.3826456e-10
4.037597e-10
2.2794566e-10
1.2494272e-10
7.614176e-11
3.9594994e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11
2.2052582e-11

In [3]:
print(sess.run((y_pred,y_true)))

(array([[-7.4505806e-06],
       [-1.0000035e+00],
       [-1.9999995e+00],
       [-2.9999955e+00]], dtype=float32), array([[ 0.],
       [-1.],
       [-2.],
       [-3.]], dtype=float32))

## Tensor and Variable Notes

<ol><b>Tensors</b>
    <li>Tensors are the basic units of TF and they hold a value</li>
    <li>Tensors have ranks that implies their dimensionality</li>
    <li>Operations on tensors can be activated only by running sessions on them</li>
    <li>Different sessions will activate different values for a tensor if initialized as random or data</li>
</ol>

<ol><b>Variables</b>
    <li>Variables are container classes for tensors</li>
    <li>They also hold values but these mutations are visible across sessions</li>
    <li>Create a variable using get_variable("name",shape)</li>
    <li>Variables are usually initialised with glorot_uniform</li>
    <li>There are 2 collection lists - Global and Trainable</li>
    <li>Use global_variables_initializer() always before training to initialize all values</li>
    <li>Sharing variables by either passing it or by using scope</li>
    <li>Scope is useful when the same code needs to be used for different purposes like a cnn layer code but you want to create multiple layers with same config then use multiple scopes calling the same function!</li>
    <li>You can also reuse scope variables by saying scope.reuse_variables()</li>
</ol>

## Basic TF model creation with data feeding and custom training

In [6]:
iris = pd.read_csv("Iris.csv",index_col=0)

In [8]:
iris.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
names = list(iris['Species'].unique())
for i in range(len(names)):
    iris.replace(names[i],i,inplace=True)

In [15]:
iris.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id
1             5.1           3.5            1.4           0.2        0
2             4.9           3.0            1.4           0.2        0
3             4.7           3.2            1.3           0.2        0
4             4.6           3.1            1.5           0.2        0
5             5.0           3.6            1.4           0.2        0